name: icc_apps
services:
  annuaire:
      #image: iccbrx/${ANNUAIRE_NAME}:${TAG}
      build: 
        context: ../../pei_server/annuaire
        target: annuaire
      container_name: ${ANNUAIRE_NAME}
      networks:
        icc_apps_net:
          ipv4_address: ${ANNUAIRE_IP}
      ports:
        - ${ANNUAIRE_PORT}:${ANNUAIRE_PORT}
      environment:
        - GatewayAddress=${GATEWAY_IP}:${GATEWAY_PORT}
        - AnnuaireAddress=${ANNUAIRE_IP}:${ANNUAIRE_PORT}
        - AnnuaireDatabaseAddress=${SURREALDB_IP}:${SURREALDB_PORT_IN}
        - GATEWAY_IP=${GATEWAY_IP}
        - ANNUAIRE_DB_NS=${ANNUAIRE_DB_NS}
        - ANNUAIRE_DB_DB=${ANNUAIRE_DB_DB}
        - SURREALDB_ROOT_USER=${SURREALDB_ROOT_USER}
        - SURREALDB_ROOT_PASSWORD=${SURREALDB_ROOT_PASSWORD}
      depends_on:
        - ${SURREALDB_NAME}

  mjib:
      #image: iccbrx/${MJIB_NAME}:${TAG}
      build: 
        context: ../../pei_server/mjib
        target: mjib
      container_name: ${MJIB_NAME}
      networks:
        icc_apps_net:
          ipv4_address: ${MJIB_IP}
      ports:
        - ${MJIB_PORT}:${MJIB_PORT}
      environment:
        - GatewayAddress=${GATEWAY_IP}:${GATEWAY_PORT}
        - MjibAddress=${MJIB_IP}:${MJIB_PORT}
        - MjibDBAddress=${SURREALDB_IP}:${SURREALDB_PORT_IN}
        - GATEWAY_IP=${GATEWAY_IP}
        - Mjib_DB_NS=${Mjib_DB_NS}
        - Mjib_DB_DB=${Mjib_DB_DB}
        - Mjib_ACCESS_METHOD=${Mjib_ACCESS_METHOD}
        - SURREALDB_ROOT_USER=${SURREALDB_ROOT_USER}
        - SURREALDB_ROOT_PASSWORD=${SURREALDB_ROOT_PASSWORD}
      depends_on:
        - ${SURREALDB_NAME}

  gateway:
      #image: iccbrx/${GATEWAY_NAME}:${TAG}
      build: 
        context: ../../pei_server/gateway
        target: gateway
      container_name: ${GATEWAY_NAME}
      networks:
        icc_apps_net:
          ipv4_address: ${GATEWAY_IP}
      ports:
        - ${GATEWAY_PORT}:${GATEWAY_PORT}
      environment:
        - GatewayAddress=${GATEWAY_IP}:${GATEWAY_PORT}
        - AnnuaireAddress=${ANNUAIRE_IP}:${ANNUAIRE_PORT}
        - MjibAddress=${MJIB_IP}:${MJIB_PORT}
      depends_on:
        - ${MJIB_NAME}
  surrealdb:
    user: ":" # this is important, if not you will face permission denied issue
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - ${SURREALDB_ROOT_USER}
      - --pass
      - ${SURREALDB_ROOT_PASSWORD}
      - rocksdb:/var/lib/surreal
    image: surrealdb/surrealdb:latest
    volumes:
      - ./databases/surreal:/var/lib/surreal
    container_name: ${SURREALDB_NAME}
    networks:
      icc_apps_net:
        ipv4_address: ${SURREALDB_IP}
    ports:
      - ${SURREALDB_PORT}:${SURREALDB_PORT_IN}

  #portal:
      #image: iccbrx/portal_dev:${TAG}
  #    build: 
  #      context: ../../pei_v2/front/portal/
  #    container_name: portal
  #    networks:
  #      icc_apps_net:
  #        ipv4_address: ${PORTAL_IP}
  #    ports:
  #    - "5173:3000"

networks:
  icc_apps_net:
    ipam:
      driver: default
      config:
          - 
            subnet: ${ICC_NETWORK}