name: icc_apps
services:
  icc_nginx:
      image: iccbrx/icc_nginx:latest
      container_name: icc_nginx
      networks:
        icc_apps_net:
          ipv4_address: ${NGINX_IP}
      ports:
      - "80:80"
      - 443:443
      restart: always
      volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  surrealdb:
    user: ":" # this is important, if not you will face permission denied issue
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - ${SURREALDB_ROOT_USER}
      - --pass
      - ${SURREALDB_ROOT_PASSWORD}
      - rocksdb:/var/lib/surreal
    image: surrealdb/surrealdb:latest
    volumes:
      - ./databases/surreal:/var/lib/surreal
    container_name: ${SURREALDB_NAME}_${SURREALDB_TAG}
    networks:
      icc_apps_net:
        ipv4_address: ${SURREALDB_IP}
    ports:
      - ${SURREALDB_PORT}:8000

  portal:
      image: iccbrx/portal_dev:${TAG}
      #build: 
        #context: ../pei_v2/front/portal/
      container_name: portal
      networks:
        icc_apps_net:
          ipv4_address: ${PORTAL_IP}
      ports:
      - "5173:3000"

networks:
  icc_apps_net:
    ipam:
      driver: default
      config:
          - 
            subnet: ${ICC_NETWORK}