name: icc_apps_${TAG}
services:
  mjib:
      image: iccbrx/${MJIB_NAME}:${TAG}
      container_name: ${MJIB_NAME}_${TAG}
      networks:
        icc_apps_dev_net:
          ipv4_address: ${MJIB_IP}
      ports:
        - ${MJIB_PORT}:${MJIB_PORT}
      environment:
        - GatewayAddress=${GATEWAY_IP}:${GATEWAY_PORT}
        - MjibAddress=${MJIB_IP}:${MJIB_PORT}
        - MjibDBAddress=${SURREALDB_IP}:${SURREALDB_PORT_IN}
        - GATEWAY_IP=${GATEWAY_IP}
        - Mjib_DB_NS=${Mjib_DB_NS}
        - Mjib_DB_DB=${Mjib_DB_DB}
        - Mjib_ACCESS_METHOD=${Mjib_ACCESS_METHOD}
        - SURREALDB_ROOT_USER=${SURREALDB_ROOT_USER}
        - SURREALDB_ROOT_PASSWORD=${SURREALDB_ROOT_PASSWORD}
      depends_on:
        - ${SURREALDB_NAME}

  gateway:
      image: iccbrx/${GATEWAY_NAME}:${TAG}
      container_name: ${GATEWAY_NAME}_${TAG}
      networks:
        icc_apps_dev_net:
          ipv4_address: ${GATEWAY_IP}
      ports:
        - ${GATEWAY_PORT}:${GATEWAY_PORT}
      environment:
        - GatewayAddress=${GATEWAY_IP}:${GATEWAY_PORT}
        - AnnuaireAddress=${ANNUAIRE_IP}:${ANNUAIRE_PORT}
        - MjibAddress=${MJIB_IP}:${MJIB_PORT}
      depends_on:
        - ${MJIB_NAME}
  surrealdb:
    user: ":" # this is important, if not you will face permission denied issue
    entrypoint: 
      - /surreal 
      - start 
      - --user
      - ${SURREALDB_ROOT_USER}
      - --pass
      - ${SURREALDB_ROOT_PASSWORD}
      - rocksdb:/var/lib/surreal
    image: surrealdb/surrealdb:latest
    volumes:
      - ./databases/surreal:/var/lib/surreal
    container_name: ${SURREALDB_NAME}_${TAG}
    networks:
      icc_apps_dev_net:
        ipv4_address: ${SURREALDB_IP}
    ports:
      - ${SURREALDB_PORT}:${SURREALDB_PORT_IN}

networks:
  icc_apps_dev_net:
    ipam:
      driver: default
      config:
          - 
            subnet: ${ICC_NETWORK}